function analysis_dir = name_analysis_dir(cfg)
% create name of the folder given the GLM configuraton

analysis_dir = [ ...
    'GLM_' ...
    'despike-' num2str(cfg.despiked) '_' ...
    'st-' num2str(cfg.slice_reference) '_' ...
    'res-' num2str(cfg.norm_res) '_' ...
    'denoise-' num2str(cfg.GLM_denoise) '_' ...
    'HPF-' sprintf('%03.0f',cfg.HPF) '_' ...
    'onset-' cfg.stim_onset '_' ...
    'RT-' num2str(cfg.RT_correction) '_' ...
    'block-' cfg.block_type '_' ...
    'timeder-' num2str(cfg.time_der) '_' ...
    'mvt-' num2str(cfg.mvt) '_' ...
    'concat-' num2str(cfg.concat) ...
    ];

fprintf('\n\nRunning %s\n\n', analysis_dir)

end

